### PR TITLE
Fixed error throwing when trying to fetch a nonexistent key

### LINKED ISSUE #3: Check whether it's undefined when fetching
ref. branch v4

I'm not sure whether v4 is checking if the row id is undefined. If so, it's good to check and return undefined beforehand

### PR DESCRIPTION
**Pull request by QSmally**
Error would be thrown if you'd fetch a row which didn't exist. It now returns either `undefined` or `null`, based on if it were to be undefined, or if the row contained a nil value

Also fixed path casting when you'd create an object but the row didn't exist

Resolves #3

### CODE REVIEW

File: lib/Connection.js [hunk 1]
```diff
@@ -281,10 +281,13 @@ class Connection extends BaseConnection {
...
-        let Fetched = this.Cache.has(Key) ? this.Cache.resolve(Key) :
-        JSON.parse(this.API.prepare(`SELECT * FROM '${this.Table}' WHERE Key = ?;`).get(Key)["Val"]);
+        let Fetched = this.Cache.resolve(Key) || (() => {
+            const Req = this.API.prepare(`SELECT * FROM '${this.Table}' WHERE Key = ?;`).get(Key);
+            if (typeof Req !== "undefined") return JSON.parse(Req.Val);
+            else return Req;
+        })();
 
-        if (typeof Fetched === "undefined") return undefined;
+        if (Fetched === null || Fetched === undefined) return Fetched;
```
Comment (QSmally) [inline lib/Connection.js:290]: If the row was `null`, it would return null. And if the row didn't exist in the database, it would return `undefined`
